### ISSUE TITLE
Pre-trained model not found (404 Not Found)

### ISSUE THREAD

**Issue by bnsblue** [wanglimin/MRCNN-Scene-Recognition#10]
Hi,

I tried to download the pre-trained knowledge models and reference models using the scripts `get_init_models.sh` and `get_reference_models.sh` but all the model files are missing (404 Not Found Error).

Could you please let me know the correct url of these models so that I can download them? Thanks so much!

**Comment by wanglimin** [comment]
I have fixed this issue. Please try again.

**Comment by fangchao** [comment]
It seems that it still not works. I can't download pre-trained model either.
